### ISSUE TITLE
About ignoring the specified network card configuration

### ISSUE THREAD

**Issue by janyyy** [fmcejudo/quarkus-eureka#37]
I have a question now, I want to use the eth0 network card address, but the docker0 network card address used during registration, is there any configuration that can ignore the specified network card? For example Spring configuration

![image](https://user-images.githubusercontent.com/27274865/153802051-3eac8690-8238-4a44-83d9-190796fa4c15.png)

**Comment by framcejudo** [comment]
Hi, thanks for that! I didn't know that property and I have suffered the same problem at some point. I can give it a try and see if I can do something similar.

Cheers.

**Comment by janyyy** [comment]
ok, thank you very much !

**Comment by fmcejudo** [comment]
Hi @janyyy , I have implemented a solution for ignoring network interfaces issue, this is in branch `ignore_network_interfaces` and there is PR in:

https://github.com/fmcejudo/quarkus-eureka/pull/38

Would you mind to give it a try and check if it meets with your requirements?

Just pull the branch, build it (mvn clean install) and use version `0.0.15-SNAPSHOT` in your project to check if it works in your project. 

If so, please let me know and I will merge this branch into master and make a new release.

And again, thanks for that issue!

Cheers.

**Comment by janyyy** [comment]
Great, I'll get back to you after testing

**Comment by janyyy** [comment]
Hi @fmcejudo @framcejudo 
I have tested that the specified network card can be ignored, and everything is normal. But Spring supports regular expressions. It means that the network card name can be ignored or specified by regular expressions. If I want to specify the eth0 network card, what should I do?

**Comment by fmcejudo** [comment]
Hi @janyyy 

You might configure your application.properties with:

`quarkus.eureka.ignore-network-interfaces=eth0`
`quarkus.http.host=0.0.0.0` -> tell quarkus to use any ip, else your quarkus app might be listening at 127.0.0.1 and health endpoints are not reached.

and don't forget to remove 

`quarkus.eureka.hostname` -> this is the default value for hostname and takes priority over others. Might this be confusing? Perhaps I have to look for other options and check. At the moment it is like this.

Cheers.

**Comment by janyyy** [comment]
@fmcejudo

**Comment by janyyy** [comment]
@fmcejudo 
I found that after I use `quarkus.arc.unremovable-types` configuration, the HostName of quarkus-eurake `registration and health` check is wrong

**Comment by fmcejudo** [comment]
Not sure about it, can you try with `preferIpAddress`?

`quarkus.eureka.prefer-ip-address` (= true)  ->Determines if the local ip address should be used instead of the hostName.

**Comment by janyyy** [comment]
Ok，I will try it two days

**Comment by janyyy** [comment]
@fmcejudo  I tested it and setting `prefer-ip-address=true` works. The registry is also registered by IP. Below is a screenshot of my configuration and registry. 
```
#    arc:
#      unremovable-types: com.xxl.**,com.sengi.job.**,com.sengi.service.**
    eureka:
      context-path: ${quarkus.http.root-path:/}
      health-check-url: /info/health
      home-page-url: /
      name: ${quarkus.application.name}
      port: ${quarkus.http.port}
      prefer-ip-address: true
      status-page-url: /info/status
      region: default
      #      ignore-network-interfaces: docker0,br-2b644052f6b2
      prefer-same-zone: true
      should-use-dns: false
      service-url:
        default: http://sengi:dev1234@192.168.10.9:18089/eureka/
```

![image](https://user-images.githubusercontent.com/27274865/156103433-b8c397f5-f852-4a14-8201-28ab01a91a9c.png)
